// Package mountable holds the third-party notices compiled into the
// mountable CLI. THIRD_PARTY_NOTICES is generated by tools/notices.
package mountable

import _ "embed"

// ThirdPartyNotices are the licenses and notices of the third-party code
// compiled into the CLI.
//
//go:embed THIRD_PARTY_NOTICES
var ThirdPartyNotices string
