// Command notices writes THIRD_PARTY_NOTICES: the license and NOTICE files of
// every module compiled into cmd/mountable on the release platforms, and the
// Go distribution's license.
//
//	go run ./tools/notices > THIRD_PARTY_NOTICES
package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

// The platforms the release builds; their dependency graphs differ.
var platforms = []string{"linux/amd64", "linux/arm64", "darwin/amd64", "darwin/arm64"}

const rule = "================================================================================"

type module struct {
	Path    string
	Version string
	Dir     string
	Main    bool
	Replace *module
}

type pkg struct {
	Dir      string
	Standard bool
	Module   *module
}

func main() {
	if err := run(os.Stdout); err != nil {
		fmt.Fprintln(os.Stderr, "notices:", err)
		os.Exit(1)
	}
}

func run(out io.Writer) error {
	// module path -> the license and notice files found for it.
	files := map[string]map[string]bool{}
	versions := map[string]string{}
	for _, platform := range platforms {
		pkgs, err := listDeps(platform)
		if err != nil {
			return err
		}
		for _, p := range pkgs {
			if p.Standard || p.Module == nil || p.Module.Main {
				continue
			}
			m := p.Module
			if m.Replace != nil {
				m = m.Replace
			}
			if files[m.Path] == nil {
				files[m.Path] = map[string]bool{}
			}
			versions[m.Path] = m.Version
			for _, f := range noticeFiles(m.Dir, p.Dir) {
				files[m.Path][f] = true
			}
		}
	}
	goroot, err := exec.Command("go", "env", "GOROOT").Output()
	if err != nil {
		return err
	}

	fmt.Fprintln(out, "Third-party notices for the mountable CLI")
	fmt.Fprintln(out)
	fmt.Fprintln(out, "The mountable binary includes the third-party software listed below.")
	fmt.Fprintln(out, "Each entry reproduces that software's license and NOTICE files.")
	fmt.Fprintln(out, "Generated by tools/notices; do not edit.")
	if err := section(out, "The Go standard library and runtime", "", []string{filepath.Join(strings.TrimSpace(string(goroot)), "LICENSE")}); err != nil {
		return err
	}
	paths := make([]string, 0, len(files))
	for p := range files {
		paths = append(paths, p)
	}
	sort.Strings(paths)
	for _, p := range paths {
		list := make([]string, 0, len(files[p]))
		for f := range files[p] {
			list = append(list, f)
		}
		if len(list) == 0 {
			return fmt.Errorf("%s: no license file found", p)
		}
		sort.Strings(list)
		if err := section(out, p, versions[p], list); err != nil {
			return err
		}
	}
	return nil
}

func listDeps(platform string) ([]pkg, error) {
	cmd := exec.Command("go", "list", "-deps", "-json=Dir,Standard,Module", "./cmd/mountable")
	goos, goarch, _ := strings.Cut(platform, "/")
	cmd.Env = append(os.Environ(), "GOOS="+goos, "GOARCH="+goarch, "CGO_ENABLED=0")
	cmd.Stderr = os.Stderr
	data, err := cmd.Output()
	if err != nil {
		return nil, fmt.Errorf("go list for %s: %w", platform, err)
	}
	var pkgs []pkg
	decoder := json.NewDecoder(bytes.NewReader(data))
	for {
		var p pkg
		err := decoder.Decode(&p)
		if errors.Is(err, io.EOF) {
			return pkgs, nil
		}
		if err != nil {
			return nil, err
		}
		pkgs = append(pkgs, p)
	}
}

// noticeFiles returns the license and notice files in dir and its parents up
// to the module root.
func noticeFiles(root, dir string) []string {
	var found []string
	for {
		entries, _ := os.ReadDir(dir)
		for _, e := range entries {
			if e.Type().IsRegular() && isNotice(e.Name()) {
				found = append(found, filepath.Join(dir, e.Name()))
			}
		}
		if dir == root || !strings.HasPrefix(dir, root) {
			return found
		}
		dir = filepath.Dir(dir)
	}
}

func isNotice(name string) bool {
	upper := strings.ToUpper(name)
	for _, prefix := range []string{"LICENSE", "LICENCE", "COPYING", "NOTICE"} {
		if strings.HasPrefix(upper, prefix) && !strings.HasSuffix(upper, ".GO") {
			return true
		}
	}
	return false
}

// section writes one component's files, each labelled by its path in the
// module.
func section(out io.Writer, name, version string, list []string) error {
	fmt.Fprintln(out)
	fmt.Fprintln(out, rule)
	fmt.Fprintln(out, strings.TrimSpace(name+" "+version))
	fmt.Fprintln(out, rule)
	for _, f := range list {
		text, err := os.ReadFile(f)
		if err != nil {
			return err
		}
		fmt.Fprintf(out, "\n--- %s ---\n\n%s\n", relativeToModule(f), strings.TrimRight(string(text), "\n"))
	}
	return nil
}

// relativeToModule turns .../mod/github.com/x/y@v1.2.3/sub/LICENSE into
// sub/LICENSE, so the output does not depend on the module cache location.
func relativeToModule(f string) string {
	slash := filepath.ToSlash(f)
	at := strings.LastIndex(slash, "@")
	if at < 0 {
		return filepath.Base(f)
	}
	rest := slash[at:]
	if i := strings.Index(rest, "/"); i >= 0 {
		return rest[i+1:]
	}
	return filepath.Base(f)
}
