// Command notices writes THIRD_PARTY_NOTICES: the license and NOTICE files of
// every module compiled into cmd/mountable on the release platforms, the
// license headers of compiled-in source files whose copyright the module's
// license files do not already carry (code under another license or
// attribution), and the Go distribution's license.
//
//	go run ./tools/notices > THIRD_PARTY_NOTICES
package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

// The platforms the release builds; their dependency graphs differ.
var platforms = []string{"linux/amd64", "linux/arm64", "darwin/amd64", "darwin/arm64"}

const rule = "================================================================================"

type module struct {
	Path    string
	Version string
	Dir     string
	Main    bool
	Replace *module
}

type pkg struct {
	Dir      string
	GoFiles  []string
	Standard bool
	Module   *module
}

func main() {
	if err := run(os.Stdout); err != nil {
		fmt.Fprintln(os.Stderr, "notices:", err)
		os.Exit(1)
	}
}

func run(out io.Writer) error {
	// module path -> the license and notice files found for it.
	files := map[string]map[string]bool{}
	sources := map[string]map[string]bool{} // module path -> compiled-in .go files
	roots := map[string]string{}
	versions := map[string]string{}
	for _, platform := range platforms {
		pkgs, err := listDeps(platform)
		if err != nil {
			return err
		}
		for _, p := range pkgs {
			if p.Standard || p.Module == nil || p.Module.Main {
				continue
			}
			m := p.Module
			if m.Replace != nil {
				m = m.Replace
			}
			if files[m.Path] == nil {
				files[m.Path] = map[string]bool{}
				sources[m.Path] = map[string]bool{}
			}
			versions[m.Path] = m.Version
			roots[m.Path] = m.Dir
			for _, f := range p.GoFiles {
				sources[m.Path][filepath.Join(p.Dir, f)] = true
			}
			for _, f := range noticeFiles(m.Dir, p.Dir) {
				files[m.Path][f] = true
			}
		}
	}
	goroot, err := exec.Command("go", "env", "GOROOT").Output()
	if err != nil {
		return err
	}

	fmt.Fprintln(out, "Third-party notices for the mountable CLI")
	fmt.Fprintln(out)
	fmt.Fprintln(out, "The mountable binary includes the third-party software listed below.")
	fmt.Fprintln(out, "Each entry reproduces that software's license and NOTICE files.")
	fmt.Fprintln(out, "Generated by tools/notices; do not edit.")
	if err := section(out, "The Go standard library and runtime", "", []string{filepath.Join(strings.TrimSpace(string(goroot)), "LICENSE")}); err != nil {
		return err
	}
	paths := make([]string, 0, len(files))
	for p := range files {
		paths = append(paths, p)
	}
	sort.Strings(paths)
	for _, p := range paths {
		list := make([]string, 0, len(files[p]))
		for f := range files[p] {
			list = append(list, f)
		}
		if len(list) == 0 {
			return fmt.Errorf("%s: no license file found", p)
		}
		sort.Strings(list)
		if err := section(out, p, versions[p], list); err != nil {
			return err
		}
		headers, err := fileHeaders(roots[p], list, sources[p])
		if err != nil {
			return err
		}
		for _, h := range headers {
			fmt.Fprintf(out, "\n--- file notice: %s ---\n\n%s\n", strings.Join(h.files, ", "), h.text)
		}
	}
	return nil
}

type fileHeader struct {
	text  string
	files []string
}

// fileHeaders returns the distinct leading comments of sources with a
// copyright line that no copyright line of the module's license files
// (licenses) carries.
func fileHeaders(root string, licenses []string, sources map[string]bool) ([]fileHeader, error) {
	var known strings.Builder
	for _, f := range licenses {
		text, err := os.ReadFile(f)
		if err != nil {
			return nil, err
		}
		for _, line := range strings.Split(string(text), "\n") {
			if i := strings.Index(strings.ToLower(line), "copyright"); i >= 0 {
				known.WriteString(normalize(line[i:]))
				known.WriteString("\n")
			}
		}
	}
	byText := map[string]*fileHeader{}
	var order []string
	paths := make([]string, 0, len(sources))
	for f := range sources {
		paths = append(paths, f)
	}
	sort.Strings(paths)
	for _, f := range paths {
		source, err := os.ReadFile(f)
		if err != nil {
			return nil, err
		}
		header := leadingComment(string(source))
		if !foreignCopyright(header, known.String()) {
			continue
		}
		rel, _ := filepath.Rel(root, f)
		if byText[header] == nil {
			byText[header] = &fileHeader{text: header}
			order = append(order, header)
		}
		byText[header].files = append(byText[header].files, filepath.ToSlash(rel))
	}
	headers := make([]fileHeader, 0, len(order))
	for _, text := range order {
		headers = append(headers, *byText[text])
	}
	return headers, nil
}

// leadingComment is the comment text before the package clause, without
// build constraints.
func leadingComment(source string) string {
	var lines []string
	for _, line := range strings.Split(source, "\n") {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "package ") {
			break
		}
		if strings.HasPrefix(trimmed, "//go:build") || strings.HasPrefix(trimmed, "// +build") {
			continue
		}
		lines = append(lines, strings.TrimRight(line, " \t\r"))
	}
	return strings.Trim(strings.Join(lines, "\n"), "\n")
}

// foreignCopyright reports whether a line of header mentioning copyright
// says something the module's license copyright lines (known, normalized) do
// not.
func foreignCopyright(header, known string) bool {
	for _, line := range strings.Split(header, "\n") {
		i := strings.Index(strings.ToLower(line), "copyright")
		if i < 0 {
			continue
		}
		if claim := normalize(line[i:]); claim != "" && !strings.Contains(known, claim) {
			return true
		}
	}
	return false
}

var (
	noise      = regexp.MustCompile(`copyright|\(c\)|©|all rights reserved|[0-9]{4}(\s*[-,]\s*[0-9]{4})*|<[^>]*>|[.,*/]`)
	whitespace = regexp.MustCompile(`\s+`)
)

// normalize lowercases text and drops years, (c) marks, e-mail addresses and
// punctuation, so the same holder matches across files and license texts.
func normalize(text string) string {
	text = noise.ReplaceAllString(strings.ToLower(text), " ")
	return strings.TrimSpace(whitespace.ReplaceAllString(text, " "))
}

func listDeps(platform string) ([]pkg, error) {
	cmd := exec.Command("go", "list", "-deps", "-json=Dir,GoFiles,Standard,Module", "./cmd/mountable")
	goos, goarch, _ := strings.Cut(platform, "/")
	cmd.Env = append(os.Environ(), "GOOS="+goos, "GOARCH="+goarch, "CGO_ENABLED=0")
	cmd.Stderr = os.Stderr
	data, err := cmd.Output()
	if err != nil {
		return nil, fmt.Errorf("go list for %s: %w", platform, err)
	}
	var pkgs []pkg
	decoder := json.NewDecoder(bytes.NewReader(data))
	for {
		var p pkg
		err := decoder.Decode(&p)
		if errors.Is(err, io.EOF) {
			return pkgs, nil
		}
		if err != nil {
			return nil, err
		}
		pkgs = append(pkgs, p)
	}
}

// noticeFiles returns the license and notice files in dir and its parents up
// to the module root.
func noticeFiles(root, dir string) []string {
	var found []string
	for {
		entries, _ := os.ReadDir(dir)
		for _, e := range entries {
			if e.Type().IsRegular() && isNotice(e.Name()) {
				found = append(found, filepath.Join(dir, e.Name()))
			}
		}
		if dir == root || !strings.HasPrefix(dir, root) {
			return found
		}
		dir = filepath.Dir(dir)
	}
}

func isNotice(name string) bool {
	upper := strings.ToUpper(name)
	for _, prefix := range []string{"LICENSE", "LICENCE", "COPYING", "NOTICE"} {
		if strings.HasPrefix(upper, prefix) && !strings.HasSuffix(upper, ".GO") {
			return true
		}
	}
	return false
}

// section writes one component's files, each labelled by its path in the
// module.
func section(out io.Writer, name, version string, list []string) error {
	fmt.Fprintln(out)
	fmt.Fprintln(out, rule)
	fmt.Fprintln(out, strings.TrimSpace(name+" "+version))
	fmt.Fprintln(out, rule)
	for _, f := range list {
		text, err := os.ReadFile(f)
		if err != nil {
			return err
		}
		fmt.Fprintf(out, "\n--- %s ---\n\n%s\n", relativeToModule(f), strings.TrimRight(string(text), "\n"))
	}
	return nil
}

// relativeToModule turns .../mod/github.com/x/y@v1.2.3/sub/LICENSE into
// sub/LICENSE, so the output does not depend on the module cache location.
func relativeToModule(f string) string {
	slash := filepath.ToSlash(f)
	at := strings.LastIndex(slash, "@")
	if at < 0 {
		return filepath.Base(f)
	}
	rest := slash[at:]
	if i := strings.Index(rest, "/"); i >= 0 {
		return rest[i+1:]
	}
	return filepath.Base(f)
}
